name: StartTheSMP
version: 2.0.0
main: com.smpstart.SMPStartPlugin
api-version: '1.21'
author: YourName
description: Start The SMP - Production-ready SMP start plugin with countdown and world border management
website: https://github.com/yourusername/startthesmp

commands:
  smpstart:
    description: Start the SMP with countdown and world border expansion
    usage: /smpstart [center|starting|start|stop|reset|reload|help]
    permission: smpstart.admin
    permission-message: "§cYou don't have permission to start the SMP!"

permissions:
  smpstart.admin:
    description: Allows starting the SMP
    default: op
